global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "192.168.1.81:9090" ]

  - job_name: "minecraft"
    static_configs:
      # Put your Minecraft server hosts here.
      # Ensure that the exporter port is accessible from prometheus.
      - targets:
          - "192.168.1.81:9100"